// Gather Arguments
const fs = require('fs'),
    PEGGY_VESION = '5.1.0',
    peggy = require('./peggy-' + PEGGY_VESION + '.min.js'),
    args = process.argv.splice(2),
    grammarFile = args[0];

let indentLevel = 0;
const indent = (txt, adj = 0) => {
    indentLevel = Math.max(0, indentLevel + adj);
    return '  '.repeat(indentLevel) + txt;
};

if (!grammarFile) {
    console.error('No grammar file argument provided. Expected this as the first argument.');
    process.exit();
}

console.info('\nBuild Constraint Parser:');
const path = grammarFile + '.pegjs',
    grammar = fs.readFileSync(path, 'utf8'),
    parserSource = peggy.generate(grammar, {output:'source'});
console.info(indent('Parser Built:' + parserSource.length, 1));

console.info(indent('Creating ExpressionParser.js', 0));
const startIdx = parserSource.indexOf('class peg$SyntaxError');
let expressionParser = `/* eslint-disable */
myt.ExpressionParser = (() => {
// @generated by Peggy ${PEGGY_VESION}.
//
// https://peggyjs.org/
${parserSource.substring(startIdx, parserSource.length - 1)};`;

// Fixup a few useless things that throw build warnings.
expressionParser = expressionParser.replace('/** @type {any} */','');

const targetFile = './src/js/myt/component/ExpressionParser.js';
fs.writeFile(targetFile, expressionParser, err => {
    if (!err) {
        console.info('\nParser JS file written to: ' + targetFile + '\n');
    } else {
        console.error('\nUnable to write JS file: ' + err.message + '\n');
    }
});

// The parser's behavior is verified by src/test/tests/component/test-ExpressionParser.js
// (run via `npm test`) rather than by ad hoc output here.